stages:
  - robot

robot:
  stage: robot
  image: python:3.9
  script:
    - pip install robotframework
    - robot -d results tests/
  artifacts:
    paths:
      - results/
  only:
    - develop

    