stages:
  - test
  - deploy

test:
  stage: test
  image: python:3.9
  script:
    - pip install -r requirements.txt
    - pytest --junitxml=test-results.xml
  artifacts:
    paths:
      - test-results.xml

deploy:
  stage: deploy
  image: python:3.9
  script:
    - echo "Deploying to production..."
  only:
    - main