stages:
  - test
  - deploy

test:
  stage: test
  image: python:3.9
  script:
    - pip install pytest pytest-html
    - pytest --html=test-results.html
  artifacts:
    paths:
      - test-results.html

deploy:
  stage: deploy
  image: python:3.9
  script:
    - echo "Deploying to production..."
  only:
    - main