cache:
  paths:
    - .cache/pip

stages:
  - test
  - build

test:
  stage: test
  image: python:3.9
  parallel: 3
  script:
    - pip install pytest pytest-html
    - pytest --html=test-results-$CI_NODE_INDEX.html
  artifacts:
    paths:
      - test-results-*.html

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t my-python-app .
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker tag my-python-app $CI_REGISTRY/my-group/my-project:latest
    - docker push $CI_REGISTRY/my-group/my-project:latest